[projects]

  [projects.default]
  contents = [
    "index",
    "julia_fundamentals", 
    "arrays_visualization"
  ]

  # Full URL, required for the sitemap and robots.txt.
  online_url = "https://pankajkmishra.github.io/GeoSciML"

  # Extra directories to be copied.
  extra_directories = []

  # Port used by serve()
  port = 8004

  output_filename = "geosciml"
