[projects]

  [projects.default]
  contents = [
    "index",
    "julia_fundamentals",
    "arrays_visualization",
  ]

  # Base domain (no path)
  online_url = "https://pankajkmishra.github.io"

  # GitHub Pages repo path
  online_url_prefix = "/GeoSciML"

  # Extra directories to be copied into _build/
  extra_directories = ["assets"]



  # Port used by serve()
  port = 8004
