name: Build & Deploy Book

on:
  push:
    branches: [ main ]
    paths:
      - 'code/**'
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.10'

      - name: Cache Julia packages
        uses: julia-actions/cache@v2

      - name: Install documentation dependencies
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.instantiate()
            Pkg.precompile()
          '

      - name: Build documentation and PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs docs/make.jl

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: |
            docs/build/html
            docs/build/pdf/documenter.pdf